# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import \
    Options
from selenium.webdriver.common.action_chains import \
    ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support import \
    expected_conditions
from selenium.webdriver.support.wait import \
    WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import \
    DesiredCapabilities


class Test_pope_creat():
#     def setup_method(self, method):
#
#         self.driver = webdriver.Chrome()
#         self.driver.implicitly_wait(5)
#
#     def teardown_method(self, method):
#         self.driver.quit()

    def test_cookie(self):
        option = Options()
        option.debugger_address = '127.0.0.1:9222'
        self.driver = webdriver.Chrome(options=option)
        self.driver.get('https://work.weixin.qq.com/wework_admin/frame#inde')
        cookies = self.driver.get_cookies()
        print(cookies)
    # def test_uploadfilr(self):
    #     self.driver.get('https://work.weixin.qq.com/wework_admin/frame#inde')
    #     cookies = [{'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.ref', 'path': '/', 'secure': False, 'value': 'direct'}, {'domain': '.qq.com', 'expiry': 1598088022, 'httpOnly': False, 'name': '_gid', 'path': '/', 'secure': False, 'value': 'GA1.2.1474626948.1597978254'}, {'domain': '.work.weixin.qq.com', 'httpOnly': True, 'name': 'wwrtx.refid', 'path': '/', 'secure': False, 'value': '3413748341321210'}, {'domain': 'work.weixin.qq.com', 'expiry': 1598009778, 'httpOnly': True, 'name': 'ww_rtkey', 'path': '/', 'secure': False, 'value': '6cr8rpl'}, {'domain': '.qq.com', 'expiry': 1912665776, 'httpOnly': False, 'name': 'pac_uid', 'path': '/', 'secure': False, 'value': '0_640c65c77fcfc'}, {'domain': '.work.weixin.qq.com', 'expiry': 1629527239, 'httpOnly': False, 'name': 'Hm_lvt_9364e629af24cb52acc78b43e8c9f77d', 'path': '/', 'secure': False, 'value': '1597235602,1597978252,1597991066'}, {'domain': '.work.weixin.qq.com', 'expiry': 1600593721, 'httpOnly': False, 'name': 'wwrtx.i18n_lan', 'path': '/', 'secure': False, 'value': 'zh-cn'}, {'domain': '.qq.com', 'expiry': 2147385600, 'httpOnly': False, 'name': 'pgv_pvid', 'path': '/', 'secure': False, 'value': '1256357540'}, {'domain': '.qq.com', 'expiry': 1661073622, 'httpOnly': False, 'name': '_ga', 'path': '/', 'secure': False, 'value': 'GA1.2.1918874628.1597235604'}, {'domain': '.work.weixin.qq.com', 'expiry': 1628771597, 'httpOnly': False, 'name': 'wwrtx.c_gdpr', 'path': '/', 'secure': False, 'value': '0'}]
    #
    #     for cookie in cookies:
    #         self.driver.add_cookie(cookie)
    #     self.driver.get('https://work.weixin.qq.com/wework_admin/frame#inde')
    #     self.driver.find_element(By.CSS_SELECTOR,'.index_service_cnt_itemWrap:nth-child(2)').click()
    #     self.driver.find_element_by_id('js_upload_file_input').send_keys(r'E:\growth_autotest\learn\test_learn\testauto.xlsx')